### ISSUE TITLE
Parsing .magres files with more than 99 atoms fails

### ISSUE THREAD

**Issue by FlorianSchreiner1** [CCP-NC/magresview-2#20]
If a CASTEP 19.1 generated magres-V1.0 with more than 100 atoms of the same type is being parsed, the import fails with the error message `Error parsing file <file>: Input matrix is not symmetric `.
From my testing this is due to the fact that CASTEP prints the atom labels in a fixed width manner, leading to atoms 1-99 being written as `<label>  1` - `<label> 99` **with** spaces between `<label>` and `<index>` and atoms 100 and up as `<label>100` **without** spaces. Example files simulating this problem are attached.
Testing these files with the online version of magresview 1.6.2 results in both files being parsed correctly.
[1_atom.zip](https://github.com/CCP-NC/magresview-2/files/13170276/1_atom.zip)

**Comment by jkshenton** [comment]
Thanks for raising this issue. You're right in that this was a bug with CASTEP itself, but has been fixed from version 22.1 onwards. 

The library that parses and deals with these magres files for MagresView 2.0 is crystvis-js. I actually [added a fix](https://github.com/stur86/crystvis-js/commit/a2394ba27c213d8b80660a6ae0997a1dc7520edb) there a while back, but haven't yet updated the live version of magresview here. I will try to do that soon.

In the meantime, two possible workarounds are:
1. manually add spaces between the species labels and the indices
2. use my development fork of MagresView 2.0. It's less stable, but does parse such magres files. You can find the live version here: https://jkshenton.github.io/magresview-2/

**Comment by FlorianSchreiner1** [comment]
Thank you very much!
For now I settled on using `sed` for quickly fixing all my data. Use of `sed -ri 's/(ms|efg) ([A-Z][a-z]?)([0-9]+)/\1 \2 \3/' <file>` will modify the file inplace, substituting all badly formatted labels.
